<a href="https://colab.research.google.com/github/olfabre/LSTM_avec_Keras/blob/main/TensorFlow_with_GPU.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
#!pip install tensorflow # à charger si tensorflow n'est pas installé
# Importation des bibliothèques nécessaires
import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, TimeDistributed, Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import to_categorical

# Exemple de données
# Les séquences d'acides aminés sont représentées par des indices de 0 à 19
# Les structures secondaires sont représentées par des indices de 0 à 2
input_sequences = [
    [0, 1, 2, 3, 4],
    [5, 6, 7, 8, 9],
    [10, 11, 12, 13, 14]
]
output_sequences = [
    [0, 1, 2, 0, 1],
    [2, 0, 1, 2, 0],
    [1, 2, 0, 1, 2]
]

# Paramètres
num_amino_acids = 20  # Nombre total d'acides aminés
num_structures = 3    # Nombre total de structures secondaires
max_sequence_length = max(len(seq) for seq in input_sequences)  # Longueur maximale des séquences

# Préparation des données
input_sequences = pad_sequences(input_sequences, maxlen=max_sequence_length, padding='post')
output_sequences = pad_sequences(output_sequences, maxlen=max_sequence_length, padding='post')
output_sequences = to_categorical(output_sequences, num_classes=num_structures)

# Construction du modèle
model = Sequential()
model.add(Embedding(input_dim=num_amino_acids, output_dim=64, input_length=max_sequence_length))
model.add(LSTM(128, return_sequences=True))
model.add(TimeDistributed(Dense(num_structures, activation='softmax')))

# Compilation du modèle
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Affichage du résumé du modèle
model.summary()

# Entraînement du modèle
model.fit(input_sequences, output_sequences, epochs=10, batch_size=1)

# Prédiction avec le modèle
predictions = model.predict(input_sequences)

# Affichage des prédictions
print("Prédictions des structures secondaires :")
print(np.argmax(predictions, axis=-1))

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)              │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ lstm_1 (LSTM)                        │ ?                           │     0 (unbuilt) │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ time_distributed_1 (TimeDistributed) │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

Epoch 1/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 2s 8ms/step - accuracy: 0.4500 - loss: 1.1000
Epoch 2/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4333 - loss: 1.0962 
Epoch 3/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.4333 - loss: 1.0922 
Epoch 4/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.4917 - loss: 1.0875
Epoch 5/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.6333 - loss: 1.0848 
Epoch 6/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.6917 - loss: 1.0798
Epoch 7/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.7417 - loss: 1.0736 
Epoch 8/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - accuracy: 0.7083 - loss: 1.0648
Epoch 9/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.7417 - loss: 1.0550
Epoch 10/10
3/3 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6583 - loss: 1.0457 
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 295ms/step
Prédictions des structures secondaires :
[[0 1 1 0 1]
 [2 0 0 0 0]
 [1 2 2 2 2]]
